name: Build APK Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Secrets
      env:
        PORTSMAN_KEY: ${{ secrets.PORTSMAN_KEY }}
        PORTSMAN_PUB: ${{ secrets.PORTSMAN_PUB }}
      shell: bash
      run: |
        echo "$PORTSMAN_KEY" >> ./portsman.key
        echo "$PORTSMAN_PUB" >> ./portsman.pub

    - name: Build APKs in Docker
      run: |
         DOCKER_BUILDKIT=1 docker build --secret id=portsman_key,src="./portsman.key" \
                               --secret id=portsman_pub,src="./portsman.pub" \
                               -t alpine-apks .

    - name: Extract APKs
      run: |
        CONTAINER=$(docker create alpine-apks)
        rm -rf ./repo
        docker cp $CONTAINER:/home/builder/output ./repo
        docker rm $CONTAINER

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
        cname: portsman.anamy.gay
