name: Build APK Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Secrets
      env:
        POSTMAN_KEY: ${{ secrets.POSTMAN_KEY }}
        POSTMAN_PUB: ${{ secrets.POSTMAN_PUB }}
      run: |
        echo ${POSTMAN_KEY} > postman.key
        echo ${POSTMAN_PUB} > postman.pub

    - name: Build APKs in Docker
      run: |
         DOCKER_BUILDKIT=1 docker build --secret id=portsman_key,src="postman.key" \
                               --secret id=portsman_pub,src="postman.pub" \
                               -t alpine-apks .

    - name: Extract APKs
      run: |
        CONTAINER=$(docker create alpine-apks)
        rm -rf ./repo
        docker cp $CONTAINER:/home/builder/output ./repo
        docker rm $CONTAINER

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages